name: CI

on:
  pull_request:
    branches: [ dev ]
    types: [closed]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'Update')
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bild and deploy
        run: npm run deploy
